baseurl = "https://elisecastillo.com/"
title = "Elise Castillo, Ph.D"
copyright = "&copy; 2021 Elise Castillo"
languageCode = "en-us"
theme = "hugo-academicx"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Allow raw html for HTML5 audio player
[markup.goldmark.renderer]
  unsafe= true

[params]
  name = "Elise Castillo"
  role = "Assistant Professor of Educational Studies"
  organization = "Trinity College"
  pronouns = "<a href=\"https://www.npr.org/2021/06/02/996319297/gender-identity-pronouns-expression-guide-lgbtq\">Gender pronouns:</a> she/her/<a href=\"https://www.tagalog.com/lessons/he-she-they-siya-sila.php\">siya</a>"
  avatar = "ec.jpg"
  email = "elise.castillo@trincoll.edu"
  address = "Trinity College, Hartford, CT, USA"
  #phone = "888 888 88 88"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  # Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    #interests = ["Artificial Intelligence", "Computational Linguistics", "Information Retrieval"]
    #str_interests = "Interests"
    str_education = "Education"

    [[params.about.education]]
      course = "Ph.D in Education Policy"
      institution = "University of California, Berkeley"

    [[params.about.education]]
      course = "MA in Education Policy"
      institution = "University of California, Berkeley"

    [[params.about.education]]
      course = "MS in Teaching (Adolescent English)"
      institution = "Pace University"
      
    [[params.about.education]]
      course = "BA in English and Creative Writing"
      institution = "Barnard College"

  # Selected Publications section.
  # Section will only be displayed if there are publications with `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 10
    detailed_list = false
    title = "Recent Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:elise.castillo@trincoll.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/ecastillophd"

#  [[params.social]]
#    icon = "google-scholar"
#    icon_pack = "ai"
#    link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

#  [[params.social]]
#    icon = "github"
#    icon_pack = "fa"
#    link = "//github.com/gcushen"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

#[[menu.main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 3

#[[menu.main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5
  
[[menu.main]]
  name = "Advising"
  url = "#advising"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7
