name = "AcademicX"
license = "MIT"
licenselink = "https://github.com/xywei/hugo-academicx/blob/master/LICENSE.md"
description = "A one page personal theme for academic staff and students."
homepage = "https://github.com/xywei/hugo-academicx"
tags = ["academic", "portfolio", "responsive", "personal", "university", "minimal"]
features = ["biography", "academic interests", "research publication system", "blog"]
min_version = 0.15

[author]
  name = "Jacob Xiaoyu Wei"
  homepage = "http://wei.wxyzg.com"

# If porting an existing theme
[original]
  name = "George Cushen"
  homepage = "https://georgecushen.com"
  repo = ""
